### ISSUE TITLE
Change the zoomLevels dynamically

### ISSUE THREAD

**Issue by jordijansen** [thoun/bga-zoom#1]
I'm using this library on my latest project, and I'm automatically setting the zoom level based on the available screen width. With the onDimensionChange callback, I can set the zoom accordingly if somebody resizes their window. But I also need to update the zoomLevels, currently it is not possible to do this only when the ZoomManager is created. Would it be possible to add the zoomLevels using a function?

If you thinks this is a good idea I can see if I can make a PR for it.

```
        const maxZoomLevel = this.determineMaxZoomLevel();
        this.zoomManager = new ZoomManager({
            element: document.getElementById('canvas-table'),
            smooth: true,
            zoomLevels: this.getZoomLevels(maxZoomLevel),
            defaultZoom: maxZoomLevel,
            zoomControls: {
                color: 'black',
            },
            onDimensionsChange: (zoom) => {
                const newMaxZoomLevel = this.determineMaxZoomLevel();
                if (newMaxZoomLevel < zoom) {
                    this.zoomManager.setZoom(newMaxZoomLevel)
                    // Here, I want to call this.zoomManager.setZoomLevels(this.getZoomLevels(maxZoomLevel)) or something similar
                }
            },
        });
```

**Comment by jordijansen** [comment]
zoomLevels is currently a private field, but since that is only checked on compile time I can bypass that for now using:
```
onDimensionsChange: (zoom) => {
                if (this.zoomManager) {
                    const newMaxZoomLevel = this.determineMaxZoomLevel();
                    // @ts-ignore
                    const currentMaxZoomLevel = this.zoomManager.zoomLevels[this.zoomManager.zoomLevels.length -1];
                    if (newMaxZoomLevel != currentMaxZoomLevel) {
                        // @ts-ignore
                        this.zoomManager.zoomLevels = this.getZoomLevels(newMaxZoomLevel);
                        this.zoomManager.setZoom(newMaxZoomLevel)
                    }
                }
            },
```

So far this seems to be working pretty well. So maybe it would be as easy as just creating a setter for zoomLevels. It is important to first set the new zoomLevels before calling setZoom because that will reset the disabled state of the zoom-in / zoom-out buttons correctly.

**Comment by thoun** [comment]
I'm OK to add a setZoomLevels, feel free to make a PR for it and I'll approve it !
